/* 
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 * Author:  giorgia
 * Created: 10-mag-2017
 */

/*
Username: utente
Password: 0000
*/

CREATE  TABLE  Utente (
    utente_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY ,
    nome VARCHAR ( 64 ),
    cognome VARCHAR ( 64 ),
    email VARCHAR ( 256 ),
    urldelProfilo VARCHAR ( 256 ),
    datadinascita DATE,
    frasedipresentazione VARCHAR ( 64 ),
    password VARCHAR ( 64 )
);

CREATE  TABLE  TipoUrl (
    tipourl_id  INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    type VARCHAR(36)
);

CREATE TABLE Post (
    post_id  INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tipo INTEGER,
    FOREIGN KEY (tipo) REFERENCES TipoUrl(tipourl_id),
    contenuto_testo VARCHAR(1024),
    url VARCHAR(256),
    utente INTEGER,
    gruppo INTEGER,
    FOREIGN KEY (utente) REFERENCES Utente(utente_id)
    FOREIGN KEY (gruppo) REFERENCES Gruppo(gruppo_id),
);

CREATE TABLE Gruppo (
    gruppo_id  INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(64),
    descrizione VARCHAR(3000),
    amministratore INTEGER,
    FOREIGN KEY (amministratore) REFERENCES Utente(utente_id)
);

CREATE TABLE UtentePerGruppo (
    
    utente INTEGER,
    FOREIGN KEY (utente) REFERENCES Utente(utente_id),
    gruppo INTEGER,
    FOREIGN KEY (gruppo) REFERENCES Gruppo(gruppo_id),
    PRIMARY KEY (utente,gruppo)
);

CREATE TABLE Amicizie(
	idUtente1 INTEGER,
	idUtente2 INTEGER,
	FOREIGN KEY (idUtente1) REFERENCES Utente(utente_id),
	FOREIGN KEY (idUtente2) REFERENCES Utente(utente_id)
);


INSERT INTO Utente (id, nome,cognome, email, urldelProfilo, datadinascita, frasedipresentazione,password)
VALUES (
        0,
        'Bob',
        'Dog',
        'bobdog@hotmail.it',
        'image/dog.PNG',
        '1993-06-20',
        'Amo corrrere nei prati',
        '254866'
);

INSERT INTO Utente (id, nome,cognome, email, urldelProfilo, datadinascita, frasedipresentazione,password)
VALUES (
        1,
        'Lisa',
        'Simpson',
        'simpson.lisa@hotmail.it',
        'image/profiloLisa.PNG',
        '1990-01-14',
        'Il giallo è il mio colore preferito',
        '982547456'
        
);

INSERT INTO Utente (id, nome,cognome, email, urldelProfilo, datadinascita, frasedipresentazione,password)
VALUES (
        2,
        'Dexter',
        ' ',
        'dexter@hotmail.it',
        'image/Dexter.jpg',
        '1996-12-31',
        'Il mio laboratorio è unico',
        '58464dc4x5'
        
);

INSERT INTO Utente (id, nome,cognome, email, urldelProfilo, datadinascita, frasedipresentazione,password)
VALUES (
        3,
        'Peppa',
        ' ',
        'peppa@hotmail.it',
        'image/Peppa.png',
        '1985-05-25',
        'Non giudicate un libro dalla copertina',
        'hfgh45'
        
);



INSERT INTO TipoUrl( id,type)
VALUES(
    0,
    'NULL'
);
INSERT INTO TipoUrl( id,type)
VALUES(
    1,
    'IMAGE'
);

INSERT INTO TipoUrl( id,type)
VALUES(
    2,
    'LINK'
);

INSERT INTO Post (id ,tipo,contenuto_testo,url,utente,gruppo)
VALUES (
    default,
    0,
    'I computer sanno contare solo da 0 ad 1, il resto è professionalità.',
    '',
    0,
    1
);

INSERT INTO Post (id ,tipo,contenuto_testo,url,utente,gruppo)
VALUES (
    default,
    1,
    'Oggi è il Pi greco Day, il giorno del numero forse più importante della scienza e della nostra vita quotidiana.\n" +"Ma ciò che è più importante per mio padre è il CIBO.',
    'image/lisahomer.PNG',
    1,
    null
);


INSERT INTO Post (id ,tipo,contenuto_testo,url,utente,gruppo)
VALUES (
    default,
    2,
    'Today happened to me a horrible thing. Look here!!!!!',
    'https://www.youtube.com/watch?v=8QR-kJyZXBg',
    2,
    null
    
);

INSERT INTO Gruppo (id,nome,descrizione,amministratore)
VALUES(
    default,
    'Nerd for nerd',
    'Solo per nerd',
    3
);

INSERT INTO Gruppo (id,nome,descrizione,amministratore)
VALUES(
    default,
    'Travel',
    'Adatto a chi ama viaggiare e conoscere nuove culture',
    3
);
INSERT INTO UtentePerGruppo (utente,gruppo)
VALUES(
    0,
    1
);

INSERT INTO UtentePerGruppo (utente,gruppo)
VALUES(
    0,
    2
);

INSERT INTO UtentePerGruppo (utente,gruppo)
VALUES(
    1,
    1
);

INSERT INTO UtentePerGruppo (utente,gruppo)
VALUES(
    2,
    2
);

INSERT INTO Amicizie(idUtente1,idUtente2)
VALUES
	(0,1), (1,2), (0,2);

