/* 
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 * Author:  giorgia
 * Created: 10-mag-2017
 */

/*
Username: peppa
Password: 0000
*/

CREATE  TABLE  Utente (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY ,
    nome VARCHAR ( 64 ),
    cognome VARCHAR ( 64 ),
    email VARCHAR ( 256 ),
    urldelProfilo VARCHAR ( 256 ),
    datadinascita DATE,
    frasedipresentazione VARCHAR ( 64 ),
    password VARCHAR ( 64 )
);

CREATE  TABLE  TipoUrl (
    id  INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    type INTEGER
);

CREATE TABLE Post (
    id  INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tipo INTEGER,
    FOREIGN KEY (tipo) REFERENCES TipoUrl(id),
    contenuto_testo VARCHAR(1024),
    url VARCHAR(32),
    utente INTEGER,
    FOREIGN KEY (utente) REFERENCES Utente(id)
);

CREATE TABLE Gruppo (
    id  INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(64),
    amministratore INTEGER,
    FOREIGN KEY (amministratore) REFERENCES Utente(id)
);

CREATE TABLE UtentePerGruppo (
    
    utente INTEGER,
    FOREIGN KEY (utente) REFERENCES Utente(id),
    gruppo INTEGER,
    FOREIGN KEY (gruppo) REFERENCES Gruppo(id),
    PRIMARY KEY (utente,gruppo)
);


